version: '2'

services:

    magicodes_host:
        image: ccr.ccs.tencentyun.com/magicodes/admin.host
        environment:
            - ASPNETCORE_ENVIRONMENT=Staging
        ports:
            - "9901:80"
        volumes:
            - "./Host-Logs:/app/App_Data/Logs"

    magicodes_ui:
        image: ccr.ccs.tencentyun.com/magicodes/admin.ui
        ports:
            - "9902:80"
        volumes:
            - "./nginx.conf:/etc/nginx/nginx.conf:ro"